name: Wind River Linux CI 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run bash command
      run: echo "Hello World"
  publish:
    runs-on: [ ubuntu-latest ]
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run bash command
        run: echo "Hello World"
        
        
